# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0d9e5dd508b8b146e46c279d8ddc27a45c7f795391656bee52dd24e9d287079b09958fd279eaffd3781c0f66ec19b17af4b3a6baafb46965a0891ae144d90a0

test:
  secret_key_base: 73a3581b623a81092dc07161750cdfd23e689398dbf00a69ff3eea8f028d326fe28d05aa12301d3e64b539a36152c83c6d5b972c2df44ebb624cda29986e6454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
